sudo: required

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc-6

# Build steps
script:
  - make tests

# travis specific parameters
before_install:
  - sudo apt-get install -qq -y g++-6
