# Enable C++ support
language: cpp python

notifications:
  email: false

# Compiler selection
compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install python3

install:
  - pip3 install pathlib --user

script:
  - python3 make.py --package utils --mode test
  - python3 make.py --package first_coefficients --mode test
