# Enable C++ support
language: cpp

notifications:
  email: false

# Compiler selection
compiler:
  - gcc

install:
  - pip install pathlib --user

script:
  - python make.py --project utils --mode test
  - python make.py --project first_coefficients --mode test
