#!/bin/bash

# Genera output ed errori nella cartella corrente.
# Se non specificato diversamente output ed errori
# vengono rediretti rispettivamente nei 2 file
# convert.job.oJOBID e convert.job.eJOBID
#
#$ -cwd

cd ~/dystoNet/

# example of execution
date
source venv/bin/activate
python make.py --package optimize_RS --deps simulator utils --configs configs.json
# python3 make.py --deps first_problem utils --package first_problem/genetic_algorithm --mode run --configs sample.json
date
